sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install appjar
  - pip install scipy

script:
  - coverage run tests/DatabaseTest.py

after_success:
  - codecov